# Generated by Django 3.2 on 2021-04-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210409_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amoun',
            new_name='amount',
        ),
    ]
