# Generated by Django 3.2 on 2021-04-25 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_commect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commect',
            new_name='Comment',
        ),
    ]
