# Generated by Django 3.2 on 2021-05-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_images_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='product/')),
                ('laptop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.laptop')),
            ],
        ),
    ]
