# Generated by Django 3.2 on 2021-05-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210515_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_pdiscount_pricerice',
            new_name='discount_price',
        ),
    ]
