# Generated by Django 3.2 on 2021-05-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_auto_20210515_1651'),
        ('product', '0014_rename_new_pdiscount_pricerice_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='category',
        ),
        migrations.DeleteModel(
            name='Imagess',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
