# Generated by Django 3.2 on 2021-05-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_ar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at_ar',
            field=models.DateTimeField(auto_now_add=True, default='2020-11-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(default='2020-11-02', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
