# Generated by Django 3.2 on 2021-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210519_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_ar',
            field=models.TextField(default='laptop'),
            preserve_default=False,
        ),
    ]
