# Generated by Django 3.2 on 2021-05-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210521_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at_ar',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_ar',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_en',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount_ar',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
