# Generated by Django 3.2 on 2021-05-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210522_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='category/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20),
        ),
    ]
