# Generated by Django 3.2 on 2021-05-21 23:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210522_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='details_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_ar',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_en',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
