# Generated by Django 3.2 on 2021-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210522_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
