# Generated by Django 3.2 on 2021-06-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': 'Variants'},
        ),
    ]
