# Generated by Django 3.2 on 2021-04-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
