# Generated by Django 3.2 on 2021-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
