# Generated by Django 3.2 on 2021-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_userprofile_address_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_ar',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_ar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
