# Generated by Django 3.2 on 2021-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20210519_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_ar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_ar',
        ),
    ]
