# Generated by Django 3.2 on 2021-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_oderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
