# Generated by Django 3.2 on 2021-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_auto_20210515_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='seller',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
