# Generated by Django 3.2 on 2021-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_orderproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='seller',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
